local_repo_path = "<path_to_local_python_repo>"
runtime = "python39"
entry_point = "hello_world"
trigger_type = "pubsub"
pubsub_topic_name = "my-topic"
trigger_event_resource = "projects/my-project/topics/my-topic"
